#!/bin/sh

# Mac
if [[ "$OSTYPE" == "darwin"* ]]; then
  echo brew update start &&
    brew update &&
    brew upgrade &&
  echo brew update done;

  echo install curl and wget start &&
    brew install curl &&
    brew install wget &&
  echo install curl and wget done;

  echo install version control start &&
    brew install git &&
    brew install tig &&
  echo install version control done;

  echo install programing language start &&
    brew install goenv &&
    brew install nvm &&
    brew install pyenv &&
    brew install rbenv &&
  echo install programing language done;

  echo install web browser start &&
    brew install --cask brave-browser &&
    brew install --cask google-chrome &&
    brew install --cask firefox &&
  echo install web browser done;

  echo install editor start &&
    brew install neovim &&
    brew tap railwaycat/emacsmacport &&
    brew install emacs-mac --with-no-title-bars &&
  echo install editor done;

  echo install terminal improve start &&
    brew install zsh &&
    brew install tmux &&
    brew install the_silver_searcher &&
    brew install ripgrep &&
    brew install fzf &&
  echo install terminal improve done;

  echo install terminal application start &&
    brew install pass &&
    brew install calcurse &&
    brew install vifm &&
    brew install newsboat &&
    brew install youtube-dl &&
    brew install imagemagick &&
    brew tap zegervdv/zathura &&
    brew install zathura &&
    brew install zathura-pdf-poppler &&
  echo install terminal application done;

  echo install docker start &&
    brew install docker &&
  echo install docker done;

  echo install gui application start &&
    brew install --cask alfred &&
    brew install --cask spotify &&
    brew install --cask freemind &&
  echo install gui application done;

  echo install keymap application start &&
    brew install --cask spectacle &&
    brew install --cask hammerspoon &&
    brew install --cask karabiner-elements &&
  echo install keymap application done;

  echo install db start &&
    brew install mysql &&
    brew install postgresql &&
  echo install db done;

  [ ! -d ${XDG_CONFIG_HOME:-$HOME/.config}/rbenv ] \
    && git clone https://github.com/rbenv/rbenv.git ${XDG_CONFIG_HOME:-$HOME/.config}/rbenv \
    && cd ${XDG_CONFIG_HOME:-$HOME/.config}/rbenv && src/configure && make -C src \
    && ${XDG_CONFIG_HOME:-$HOME/.config}/rbenv/bin/rbenv init
  [ ! -d ${XDG_CONFIG_HOME:-$HOME/.config}/goenv ] \
    && git clone https://github.com/syndbg/goenv.git ${XDG_CONFIG_HOME:-$HOME/.config}/goenv
  [ ! -d ${XDG_CONFIG_HOME:-$HOME/.config}/pyenv ] \
    && git clone https://github.com/pyenv/pyenv.git ${XDG_CONFIG_HOME:-$HOME/.config}/pyenv \
    && cd ${XDG_CONFIG_HOME:-$HOME/.config}/pyenv && src/configure && make -C src
  [ ! -d ${XDG_CONFIG_HOME:-$HOME/.config}/nvm ] \
    && wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  [ ! -d ${XDG_CONFIG_HOME:-$HOME/.config}/sdkman ] \
    && curl -s "https://get.sdkman.io" | zsh \
    && mv ~/.sdkman ${XDG_CONFIG_HOME:-$HOME/.config}/sdkman

  [ ! -d ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/plugins/zsh-autosuggestions ] \
    && git clone https://github.com/zsh-users/zsh-autosuggestions ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/plugins/zsh-autosuggestions
  [ ! -d ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/plugins/fast-syntax-highlighting ] \
    && git clone https://github.com/zdharma-continuum/fast-syntax-highlighting ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/plugins/fast-syntax-highlighting
fi
